@protocol = http
@hostname = localhost
@port = 5173
@host = {{protocol}}://{{hostname}}:{{port}}

// MOTE: num run dev -- --host

// TODO: create e2e TEST CODE !!!

###
GET {{host}}

###
GET https://sinpro.dev/icon-144.avif

###
GET https://sinpro.dev/fonts/press-start-2p.woff2

###
GET http://localhost:5173/fonts/press-start-2p.woff2

###
GET https://sinpro.dev/icon-512.png
