name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.runner }}
    # strategy:
    #   matrix:
    #     runner: [ubuntu-latest, self-hosted]
    steps:
      # - run: echo 'This job is running on ${{ matrix.runner }} runner!!'

      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-and-cache

      - name: Build
        shell: bash
        run: npm run build

      - name: Lint Check
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Svelte Check
        run: npm run check

  tests:
    name: Tests
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-and-cache
        # run: npx playwright install --with-deps

      - name: Build
        shell: bash
        run: npm run build

      - name: Vitest Test
        run: npm run test:ci

      # https://playwright.dev/docs/ci-intro
      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Playwright Test
        run: npm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: logs/
          retention-days: 30
