name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Auto Review by OpenAI
        uses: akiojin/auto-review-github-action@v1.1.1
        if: github.event_name == 'pull_request'
        continue-on-error: true
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          target: 'ts,js,cjs,html,css,md,yml'
          language: 日本語
